%% DESCRIPTION
  % just returns a WCO from two input time series
function varargout = Timeseries2WCO(ts_x1, ts_x2, varargin)

disp = false;  % display options
source = 'J';  % use Matlab for Matlab implementation of the CWT
  %% continious wavelet transform
%   [cwt_1,scales,periods,coi,time] = CWT(ts_x1, ...
%                                           'wave_normalization', char(parameter_space.wave_normalization),...
%                                           'morse_space', char(parameter_space.morse_space),...
%                                           'K', 1, ...
%                                           'be', parameter_space.be,...
%                                           'ga', parameter_space.ga,...
%                                           'disp_cwt', false,...
%                                           'wavelet_type', char(parameter_space.wavelet_type),...
%                                           'source', source...
%                                           );
%   cwt_2 = CWT(ts_x2,...
%                     'wave_normalization', char(parameter_space.wave_normalization),...
%                     'morse_space', char(parameter_space.morse_space),...
%                     'K', 1, ...
%                     'be', parameter_space.be,...
%                     'ga', parameter_space.ga,...
%                     'disp_cwt', false,...
%                     'wavelet_type', char(parameter_space.wavelet_type),...
%                     'source', source...
%                     );
  [cwt_1,scales,periods,coi,time] = CWT(ts_x1,varargin);
   cwt_2 = CWT(ts_x2,varargin);
  %% wavelet coherence
%   Input_WCO = WCO(cwt_1,cwt_2,scales,periods,...
%               'smoothing', char(parameter_space.smoothing),...
%               'ws_size', parameter_space.ws_size,...
%               'wt_size', parameter_space.wt_size,...
%               'disp_coherence', false,...
%               'coi',cwt_1,...
%               'time_series',[ts_x1 ts_x2],...
%               'y_axis', 'scale',...
%               'coherence', char(parameter_space.coherence)...
%               );

 Input_WCO = WCO(cwt_1,cwt_2,scales,periods,varargin);
  varargout = {Input_WCO, periods};
  end
